### PR TITLE
bump version to v1.22.0

### PR DESCRIPTION
**Pull request by swoga**
Resolves #52.

### CODE REVIEW

**Comment by galexrt** [comment]
Thanks for the PR! There is the problem right now that due to Docker Hub having removed the auto building, the repo wouldn't be built now..
I still have to see if I'm going to pay Docker Hub for the next few months or completely switching to GitHub Actions (though using Docker / buildah through Makefile to make it easy to switch (again) in the future (if needed)).

I'll hopefully be able to get back with a solution next end of weekend.

**Comment by swoga** [comment]
Maybe move the image to Github's `ghcr.io`?

**Comment by galexrt** [comment]
@swoga Mhh good idea, I'll work on the GitHub workflows and / or Makefile magic in the coming days.

I should have something ready on the weekend so the images are continued to be built and pushed somewhere.

**Comment by galexrt** [comment]
Oh the PR got closed as I went ahead and moved the branch from `master` to `main`.

I got the CI ready now and will incorporate your changes / commit into the branch now. One thing to note is that the images are only pushed to GHCR and Quay now, as I don't like the fact of Docker Hub not allowing more than 1 access token (I like to have separate tokens per repo / image).

Thanks for the PR and feedback!

**Pull request closed without merging**
