### PR TITLE
Updating supervisord to include sendalerts

### LINKED ISSUE #11: Start sendalerts with supervisord
The current docs recommend managing the sendalerts command with supervisord.  I'm not super familiar with it, but might attempt the change and submit a PR.

### PR DESCRIPTION
**Pull request by jhnlsn**
* moved sendalerts to supervisord - log tracking is better
* Adding -c flag to supervisord call to remove log warning

Resolves #11.

### CODE REVIEW

**Comment by galexrt** [comment]
Thanks for the PR! Did you have tested your changes? If so could you post a `docker logs` of the container so I can verify, as I'm unable to test the PR until Sunday.

**Comment by jhnlsn** [comment]
Sure, I can post the logs.  I've already swapped out my container for this style in my environment and it works great.

**Comment by jhnlsn** [comment]
Here are the logs:
https://gist.github.com/jhnlsn/63c68308935998066f8a2be1247ea4bc

There is one thing remaining that I would like to figure out and it is: `2018-02-07 11:30:02,457 CRIT Supervisor running as root (no user in config file)`

There are different opinions about this but i'm just not sure what the right approach is yet.

**Comment by galexrt** [comment]
Logs LGTM

To fix `2018-02-07 11:30:02,457 CRIT Supervisor running as root (no user in config file)` a `supervisord` section with an `user` could be added, see https://github.com/Supervisor/supervisor/blob/master/supervisor/skel/sample.conf#L37.
To run this image as non-root user, I think there may be more changes required. I will look into it moving this image to non-root soon.

**Pull request merged**
