### PR TITLE
Fix current commit version invoking of manage.py

### PR DESCRIPTION
**Pull request by Braintelligence**

### CODE REVIEW

**Comment by Braintelligence** [comment]
I found out that healthchecks uses local_settings.py for database settings, so this is understood now.

**Comment by Braintelligence** [comment]
You could actually put all of your created settings into the local_settings.py it just gets integrated into the settings.py at the end of the settings.py

**Comment by Braintelligence** [comment]
The SECRET_KEY doesn't seem to appear there, though.

**Comment by galexrt** [comment]
Oh sorry. I already fixed those issues locally but haven't pushed them yet as I'm currently fixing the virtualenv removal issues.
I'm almost ready with a fix for the virtualenv removal issues.

**Comment by galexrt** [comment]
@Braintelligence The `SECRET_KEY` generation is here: https://github.com/galexrt/docker-healthchecks/blob/master/entrypoint.sh#L12

**Comment by Braintelligence** [comment]
I know but for some reason it isn't incorporated in my settings.py

**Comment by galexrt** [comment]
I'm closing this as I wrote I already made those changes locally during the rework of the image, please take a look at the latest state of the `master` branch as it also contains those changes and even more.

**Pull request closed without merging**
